import type { Resource } from "@/lib/resources/types"

const DATE = "2026-09-19"

export const RESOURCES: Resource[] = [
  {
    slug: "how-to-validate-a-business-idea",
    category: "start",
    type: "guide",
    title: "How to validate a business idea",
    description:
      "A practical way to test whether a problem is real, whether people will pay, and whether you should build before you spend weeks on the product.",
    topics: ["startup", "research", "MVP", "product"],
    difficulty: "beginner",
    readingMinutes: 8,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["start/founder-fundamentals", "build/how-to-build-an-mvp", "templates/customer-interview-template"],
    body: [
      { type: "p", text: "Validation is not a pitch deck, a logo, or a long plan. It is evidence that a specific person has a painful problem, and that your proposed solution is worth trying." },
      { type: "h2", id: "what-validation-means", text: "What validation means" },
      { type: "p", text: "You are trying to reduce the most expensive risk first: building something nobody needs. A validated idea has a clear customer, a problem they already feel, and a reason they would try your solution over what they do today." },
      { type: "h2", id: "a-simple-sequence", text: "A simple sequence" },
      { type: "ol", items: [
        "Write the problem in one sentence, naming who has it.",
        "Talk to 8–12 people in that group. Ask about the last time the problem happened, not whether they like your idea.",
        "Look at what they already pay for or spend time on.",
        "Offer a small version of the solution — a waitlist, a concierge service, or a narrow MVP — and see if anyone takes the next step.",
        "Only then expand the product.",
      ] },
      { type: "callout", kind: "warning", title: "Do not ask “Would you use this?”", text: "People are polite. Ask what they did last week, what they paid, and what they tried that failed." },
      { type: "h2", id: "enough-to-build", text: "When you have enough to build" },
      { type: "ul", items: [
        "The same problem shows up in multiple conversations.",
        "People already hack together a workaround.",
        "Someone will give you time, money, or data for an early version.",
      ] },
      { type: "callout", kind: "takeaway", title: "Key takeaway", text: "Validation is a series of small tests, not a one-time decision. Build only after the problem is specific." },
      { type: "faq", items: [
        { q: "Do I need a survey?", a: "Not first. Direct conversations beat anonymous forms when you still do not know the language customers use." },
        { q: "Should I validate before building?", a: "Yes, at least enough to name the customer and the job they need done. An MVP then tests the solution, not the existence of the problem." },
      ] },
    ],
  },
  {
    slug: "founder-fundamentals",
    category: "start",
    type: "guide",
    title: "Founder fundamentals",
    description: "The few decisions that matter early: who you serve, what you will not build, and how you will learn each week.",
    topics: ["startup", "product", "business model"],
    difficulty: "beginner",
    readingMinutes: 6,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["start/how-to-validate-a-business-idea", "build/product-requirements", "glossary/product-market-fit"],
    body: [
      { type: "p", text: "Early-stage work is mostly choosing a customer, a problem, and a constraint. Everything else is easier when those three are written down." },
      { type: "h2", id: "write-it-down", text: "Write four sentences" },
      { type: "ol", items: [
        "Who this is for.",
        "The problem they have today.",
        "The outcome they want.",
        "What you will not do in the first version.",
      ] },
      { type: "h2", id: "weekly-learning", text: "Learn on a weekly cadence" },
      { type: "p", text: "Pick one question per week: Can I find this customer? Will they try it? Will they come back? Will they pay? Answer it with a test, not a meeting." },
      { type: "callout", kind: "tip", title: "Tip", text: "If two founders cannot agree on the customer, pause feature work until they can." },
    ],
  },
  {
    slug: "how-to-build-an-mvp",
    category: "build",
    type: "guide",
    title: "How to build an MVP",
    description: "Decide what belongs in a first version, what to leave out, and how to check whether the result taught you anything.",
    topics: ["MVP", "product", "development"],
    difficulty: "beginner",
    readingMinutes: 9,
    publishedAt: DATE,
    updatedAt: DATE,
    featured: true,
    related: ["start/how-to-validate-a-business-idea", "build/product-requirements", "templates/mvp-checklist", "launch/launch-checklist"],
    body: [
      { type: "p", text: "An MVP is the smallest product that lets you test a meaningful assumption with real users. It is not a cheaper version of the full vision. It is a focused experiment." },
      { type: "h2", id: "what-is-an-mvp", text: "What is an MVP?" },
      { type: "p", text: "An MVP should complete one important job for one customer. If they can finish that job, you can learn whether the product is worth expanding." },
      { type: "h2", id: "what-to-include", text: "What to include" },
      { type: "ul", items: [
        "The core workflow that delivers the promised outcome.",
        "A way to sign in or identify the user if the job requires it.",
        "A way to see the result (a dashboard, email, export, or live URL).",
        "Enough reliability that testers are not blocked by obvious breakage.",
      ] },
      { type: "h2", id: "what-to-leave-out", text: "What to leave out" },
      { type: "ul", items: [
        "Admin tools nobody asked for.",
        "Every role, every integration, and every theme.",
        "Growth features before anyone uses the core job.",
        "Perfect visual polish that delays learning.",
      ] },
      { type: "callout", kind: "example", title: "Example", text: "A booking MVP can be “create a slot, share a link, receive a confirmation.” It does not need a full CRM, loyalty program, or multi-location reporting." },
      { type: "h2", id: "how-to-validate-the-mvp", text: "How to validate the MVP" },
      { type: "ol", items: [
        "Give it to a small group that already has the problem.",
        "Watch them complete the core job without you in the room.",
        "Ask what they would pay for, not what extra buttons they want.",
        "Keep a list of friction. Fix only what blocked the job.",
      ] },
      { type: "h2", id: "common-mistakes", text: "Common mistakes" },
      { type: "ul", items: [
        "Building a demo that cannot be used without you.",
        "Calling a slide deck an MVP.",
        "Adding features whenever a single tester asks.",
        "Never defining the assumption you are testing.",
      ] },
      { type: "callout", kind: "takeaway", title: "Key takeaway", text: "If the first version cannot teach you whether the core job works, it is not an MVP yet." },
      { type: "faq", items: [
        { q: "How long should an MVP take?", a: "As short as you can make it while still testing the real job. Timeboxes help; feature lists rarely do." },
        { q: "Should it be full-stack?", a: "If the job needs accounts, data, and a live URL, yes — those are part of the job, not extras. Decorative extras are not." },
      ] },
    ],
  },
  {
    slug: "product-requirements",
    category: "build",
    type: "playbook",
    title: "Write product requirements that can be built",
    description: "Turn a vague idea into a short spec: users, jobs, screens, and what done looks like.",
    topics: ["product", "UX", "MVP"],
    difficulty: "beginner",
    readingMinutes: 7,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["build/how-to-build-an-mvp", "atai/idea-mode", "templates/mvp-checklist"],
    body: [
      { type: "p", text: "A useful spec is short enough to read and specific enough to build. It names users, the job, the screens, and the definition of done." },
      { type: "h2", id: "minimum-spec", text: "The minimum spec" },
      { type: "ol", items: [
        "Primary user and the job they hire the product to do.",
        "The happy path, step by step.",
        "Data you must store.",
        "What “done” looks like for the first release.",
        "A list of explicit non-goals.",
      ] },
      { type: "callout", kind: "important", title: "Important", text: "If a requirement cannot be observed in the product, it is not a requirement yet. “Make it engaging” needs a behavior you can see." },
      { type: "h2", id: "keep-it-editable", text: "Keep it editable" },
      { type: "p", text: "Treat the spec as a working document. After each test, update the job, not just the feature list." },
    ],
  },
  {
    slug: "how-to-launch-a-product",
    category: "launch",
    type: "guide",
    title: "How to launch a product",
    description: "A quiet, useful launch: define the offer, pick the first audience, share the link, and learn from the first week.",
    topics: ["launch", "product", "growth"],
    difficulty: "beginner",
    readingMinutes: 7,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["launch/launch-checklist", "build/how-to-build-an-mvp", "grow/find-early-customers"],
    body: [
      { type: "p", text: "Launching is putting a working product in front of people who have the problem — then paying attention. It is not a press cycle." },
      { type: "h2", id: "define-the-offer", text: "Define the offer" },
      { type: "p", text: "Write one sentence: who it is for, the job it does, and what they do next (sign up, book, pay, or invite a teammate)." },
      { type: "h2", id: "choose-the-first-audience", text: "Choose the first audience" },
      { type: "ul", items: [
        "People you already interviewed.",
        "A community where the job is discussed every week.",
        "A short list of operators you can email personally.",
      ] },
      { type: "h2", id: "the-first-week", text: "The first week" },
      { type: "ol", items: [
        "Share a working URL, not a teaser.",
        "Ask each person to complete the core job.",
        "Note every place they got stuck.",
        "Fix blockers before adding requested extras.",
      ] },
      { type: "callout", kind: "takeaway", title: "Key takeaway", text: "A successful first launch is measured in completed jobs and honest feedback, not in impressions." },
    ],
  },
  {
    slug: "launch-checklist",
    category: "launch",
    type: "checklist",
    title: "Launch checklist",
    description: "A practical list for putting a first version in front of users without forgetting the basics.",
    topics: ["launch", "MVP", "product"],
    difficulty: "beginner",
    readingMinutes: 5,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["build/how-to-build-an-mvp", "grow/find-early-customers", "templates/mvp-checklist"],
    body: [
      { type: "p", text: "A launch is not a press event. It is the moment real people can complete the job without you sitting next to them." },
      { type: "h2", id: "before-you-share-the-link", text: "Before you share the link" },
      { type: "ul", items: [
        "The core job works on a phone and a desktop.",
        "Sign-in, reset password, and a clear empty state exist if accounts are required.",
        "You know where errors go (email, log, or a simple inbox).",
        "Pricing or access is explained in one sentence.",
        "You can name 20 people who should see it first.",
      ] },
      { type: "h2", id: "the-day-you-launch", text: "The day you launch" },
      { type: "ol", items: [
        "Send a personal note to the people you already spoke with.",
        "Watch the first sessions or ask for a five-minute call.",
        "Write down every blocker. Fix blockers before adding features.",
      ] },
      { type: "callout", kind: "tip", title: "Tip", text: "A quiet launch to 20 relevant people teaches more than a loud launch to nobody in particular." },
    ],
  },
  {
    slug: "find-early-customers",
    category: "grow",
    type: "guide",
    title: "Find early customers",
    description: "Where to look for the first users, how to ask, and how to tell a useful conversation from polite interest.",
    topics: ["growth", "marketing", "startup"],
    difficulty: "beginner",
    readingMinutes: 7,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["launch/launch-checklist", "start/how-to-validate-a-business-idea", "templates/customer-interview-template"],
    body: [
      { type: "p", text: "Early customers usually come from places you already have permission to speak: communities, previous coworkers, niche forums, and the people you interviewed during validation." },
      { type: "h2", id: "start-close", text: "Start close" },
      { type: "ul", items: [
        "People who already described the problem to you.",
        "Operators in a niche Slack, WhatsApp, or industry group.",
        "A warm introduction from someone who does the job every day.",
      ] },
      { type: "h2", id: "the-ask", text: "The ask" },
      { type: "p", text: "Ask for a specific next step: try this URL, book a 15-minute walkthrough, or reply with the last time the problem happened. Vague “check it out” messages are easy to ignore." },
      { type: "callout", kind: "warning", title: "Warning", text: "Paid ads can wait until you know the sentence that describes the problem. Otherwise you pay to learn the copy." },
    ],
  },
  {
    slug: "what-is-an-ai-agent",
    category: "ai",
    type: "guide",
    title: "What is an AI agent?",
    description: "A plain-language definition of AI agents, what they can do in a product workflow, and where a human still needs to decide.",
    topics: ["AI", "agents", "product"],
    difficulty: "beginner",
    readingMinutes: 6,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/what-is-atai", "atai/how-atai-works", "glossary/mvp"],
    body: [
      { type: "p", text: "An AI agent is software that can take a goal, use tools or context, and produce a next step — not only a paragraph of text. In a product company, that might mean researching a market, drafting a plan, or proposing a change to a codebase." },
      { type: "h2", id: "agent-vs-chat", text: "Agent vs. chatbot" },
      { type: "p", text: "A chatbot answers. An agent is expected to work toward an outcome: gather context, choose an action, and return something you can inspect. You still review the result." },
      { type: "h2", id: "where-agents-help", text: "Where agents help founders" },
      { type: "ul", items: [
        "Turning a messy idea into a structured plan.",
        "Comparing a reference website to what you actually need.",
        "Drafting requirements, copy, or a first product shape.",
        "Flagging gaps before you build.",
      ] },
      { type: "callout", kind: "important", title: "Important", text: "Agents do not replace judgment about customers, pricing, or what not to build. They compress the work around those decisions." },
    ],
  },
  {
    slug: "what-is-atai",
    category: "atai",
    type: "guide",
    title: "What is Atai?",
    description: "Atai is an AI business-building platform: plan, build, launch, manage, and grow a digital product from an idea, a URL, a website, or a GitHub repository.",
    topics: ["Atai", "AI", "product"],
    difficulty: "beginner",
    readingMinutes: 5,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/how-atai-works", "atai/getting-started-with-atai", "ai/what-is-an-ai-agent"],
    body: [
      { type: "p", text: "Atai helps you turn an idea into a real full-stack product, with infrastructure configured so you can launch and keep working in one place. You bring the intent. Atai helps with planning, building, and the path after launch." },
      { type: "h2", id: "what-you-can-start-from", text: "What you can start from" },
      { type: "ul", items: [
        "An idea you describe in your own words.",
        "A website you want Atai to understand as a reference (Mirror).",
        "A URL to analyze.",
        "A GitHub repository to import or extend.",
      ] },
      { type: "h2", id: "what-atai-is-not", text: "What Atai is not" },
      { type: "p", text: "Atai is not a promise that every business will succeed, and it is not a copy machine for other people’s products. It is a system for understanding your starting point, planning around it, and producing something you can run." },
      { type: "callout", kind: "takeaway", title: "Key takeaway", text: "Use Atai when you want a working product path — not just a mockup." },
    ],
  },
  {
    slug: "how-atai-works",
    category: "atai",
    type: "guide",
    title: "How Atai works",
    description: "The Atai path: understand the starting point, plan, assemble the right capabilities, build, then help you move forward.",
    topics: ["Atai", "product", "AI"],
    difficulty: "beginner",
    readingMinutes: 6,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/what-is-atai", "atai/getting-started-with-atai", "atai/idea-mode"],
    body: [
      { type: "p", text: "Atai is built around one loop: understand what you gave it, turn that into a plan you can review, then build toward a product you can launch." },
      { type: "h2", id: "the-loop", text: "The loop" },
      { type: "ol", items: [
        "You start with an idea, URL, reference site, or GitHub repo.",
        "Atai structures what it understood so you can correct it.",
        "You review the plan — users, pages, and behavior.",
        "When you approve, Atai scaffolds the application and infrastructure.",
        "You continue in the workspace: edit, collaborate, deploy, and grow.",
      ] },
      { type: "callout", kind: "tip", title: "Tip", text: "The plan is the product contract. Spend time there. Building faster on a vague plan only produces a vague product." },
    ],
  },
  {
    slug: "getting-started-with-atai",
    category: "atai",
    type: "tutorial",
    title: "Getting started with Atai",
    description: "Create an account, pick a starting mode, and take a first project through planning.",
    topics: ["Atai", "tutorial"],
    difficulty: "beginner",
    readingMinutes: 4,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/idea-mode", "atai/mirror-and-url-mode", "atai/github-mode"],
    body: [
      { type: "p", text: "You do not need a technical background to start. You need a problem you can describe, or a URL / repository Atai can inspect." },
      { type: "h2", id: "steps", text: "Steps" },
      { type: "ol", items: [
        "Open Atai and create an account (Google, GitHub, or email).",
        "Choose Idea, Mirror/URL, or GitHub.",
        "Describe the job or paste the link.",
        "Review what Atai understood. Edit anything that is wrong.",
        "Continue into the plan, then build when the plan matches the product you want.",
      ] },
      { type: "callout", kind: "important", title: "Important", text: "If you are mirroring a site, use it as a reference for experience and structure. Do not treat Atai as a way to copy protected content." },
    ],
  },
  {
    slug: "idea-mode",
    category: "atai",
    type: "documentation",
    title: "Idea Mode",
    description: "Start from a problem and a solution in plain language. Atai turns that into a structured plan you can review before anything is built.",
    topics: ["Atai", "product"],
    difficulty: "beginner",
    readingMinutes: 4,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/getting-started-with-atai", "build/product-requirements", "atai/mirror-and-url-mode"],
    body: [
      { type: "p", text: "Idea Mode is for when you do not have a reference site. You describe the problem, who it is for, and the solution you have in mind." },
      { type: "h2", id: "what-to-write", text: "What to write" },
      { type: "ul", items: [
        "The problem in concrete terms.",
        "Who feels it.",
        "What a good first version would let them do.",
        "Optional: business model if you already know it.",
      ] },
      { type: "p", text: "Atai uses that text to draft a plan. You should rewrite anything that does not match your intent before you build." },
    ],
  },
  {
    slug: "mirror-and-url-mode",
    category: "atai",
    type: "documentation",
    title: "Mirror and URL modes",
    description: "Give Atai a website to understand as context or inspiration, then describe what you want to create from it.",
    topics: ["Atai", "product"],
    difficulty: "beginner",
    readingMinutes: 5,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/idea-mode", "atai/github-mode", "atai/how-atai-works"],
    body: [
      { type: "p", text: "Mirror and URL modes start from a live website. Atai analyzes the site so you can adapt the experience to your business — not clone someone else’s product as-is." },
      { type: "h2", id: "when-to-use-them", text: "When to use them" },
      { type: "ul", items: [
        "You like how a product works and want a version for your market.",
        "You need Atai to understand an existing site as context.",
        "You have a URL and a sentence about what should be different.",
      ] },
      { type: "callout", kind: "warning", title: "Warning", text: "Only use sites you are allowed to study as a reference. Do not use these modes to reproduce protected content or bypass access controls." },
    ],
  },
  {
    slug: "github-mode",
    category: "atai",
    type: "documentation",
    title: "GitHub Mode",
    description: "Point Atai at a repository. Clone mode builds from the README; Extend mode continues an existing codebase.",
    topics: ["Atai", "development"],
    difficulty: "intermediate",
    readingMinutes: 5,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["atai/getting-started-with-atai", "build/how-to-build-an-mvp"],
    body: [
      { type: "p", text: "GitHub Mode is for existing code. Paste a GitHub URL or owner/repo. Public repos work as-is; private repos require a connected GitHub account with access." },
      { type: "h2", id: "clone-vs-extend", text: "Clone vs Extend" },
      { type: "ul", items: [
        "Clone: treat the README and structure as the brief for a new app.",
        "Extend: keep working in the existing codebase and describe the change you want.",
      ] },
      { type: "p", text: "This mode is marked experimental in the product. Review the plan carefully before you build." },
    ],
  },
  {
    slug: "mvp-checklist",
    category: "templates",
    type: "checklist",
    title: "MVP checklist",
    description: "A copy-paste checklist for scoping a first version you can put in front of users.",
    topics: ["MVP", "product", "template"],
    difficulty: "beginner",
    readingMinutes: 3,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["build/how-to-build-an-mvp", "launch/launch-checklist", "build/product-requirements"],
    body: [
      { type: "p", text: "Use this before you write a long feature list. Check only what is true today." },
      { type: "h2", id: "scope", text: "Scope" },
      { type: "ul", items: [
        "One primary user is named.",
        "One core job is named.",
        "Non-goals are written down.",
        "The happy path is under ten steps.",
      ] },
      { type: "h2", id: "build", text: "Build" },
      { type: "ul", items: [
        "A user can complete the job without you.",
        "Broken states have a message, not a blank screen.",
        "You can see that someone used it.",
      ] },
      { type: "h2", id: "learn", text: "Learn" },
      { type: "ul", items: [
        "You know which assumption this version tests.",
        "You have a date to review what you learned.",
      ] },
    ],
  },
  {
    slug: "customer-interview-template",
    category: "templates",
    type: "template",
    title: "Customer interview template",
    description: "Questions that uncover real behavior instead of compliments about your idea.",
    topics: ["research", "startup", "template"],
    difficulty: "beginner",
    readingMinutes: 4,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["start/how-to-validate-a-business-idea", "grow/find-early-customers"],
    body: [
      { type: "p", text: "Keep interviews under 30 minutes. Record notes in the customer’s words." },
      { type: "h2", id: "script", text: "Script" },
      { type: "ol", items: [
        "What does your work look like on a normal Tuesday?",
        "Tell me about the last time [problem] happened.",
        "What did you do? How long did it take?",
        "What have you already tried?",
        "If this disappeared tomorrow, what would break?",
        "What would a useful first version need to do — nothing more?",
      ] },
      { type: "callout", kind: "tip", title: "Tip", text: "Do not demo until the end, if at all. Demos train people to react to your solution instead of describing their problem." },
    ],
  },
  {
    slug: "mvp",
    category: "glossary",
    type: "glossary",
    title: "MVP",
    description: "Minimum Viable Product: the smallest version that tests a real product assumption with users.",
    topics: ["MVP", "glossary"],
    difficulty: "beginner",
    readingMinutes: 2,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["build/how-to-build-an-mvp", "templates/mvp-checklist", "glossary/product-market-fit"],
    body: [
      { type: "p", text: "An MVP is the smallest version of a product that allows a team to test a meaningful product assumption with real users." },
      { type: "p", text: "It should complete a job, not merely illustrate a vision. Related: How to build an MVP." },
    ],
  },
  {
    slug: "product-market-fit",
    category: "glossary",
    type: "glossary",
    title: "Product-market fit",
    description: "When a defined customer group wants the product enough to use it, keep using it, and tell you when it breaks.",
    topics: ["glossary", "startup", "growth"],
    difficulty: "intermediate",
    readingMinutes: 2,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["start/how-to-validate-a-business-idea", "grow/find-early-customers"],
    body: [
      { type: "p", text: "Product-market fit is the point where a specific market pulls the product forward: people use it, return, and care when it is down." },
      { type: "p", text: "It is observed in behavior, not declared in a pitch. Early signs include repeat use, organic referrals, and customers who complain when a core job fails." },
    ],
  },
  {
    slug: "saas",
    category: "glossary",
    type: "glossary",
    title: "SaaS",
    description: "Software as a Service: software delivered over the internet, usually paid as a subscription.",
    topics: ["SaaS", "glossary", "business model"],
    difficulty: "beginner",
    readingMinutes: 2,
    publishedAt: DATE,
    updatedAt: DATE,
    related: ["build/how-to-build-an-mvp", "atai/what-is-atai"],
    body: [
      { type: "p", text: "SaaS is software hosted by the provider and used through the browser or an API, typically billed on a subscription." },
      { type: "p", text: "For founders, the operational implication is that accounts, data, billing, and uptime are part of the product, not extras you add later." },
    ],
  },
]
